services:
  localstack:
    image: localstack/localstack:latest
    container_name: wetter-localstack
    ports:
      - "4568:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
