FROM grafana/grafana-oss:latest

COPY docker/grafana/provisioning/dashboards/dashboards.yml /etc/grafana/provisioning/dashboards/dashboards.yml
COPY grafana/dashboards/iot-wetterstation.json /var/lib/grafana/dashboards/iot-wetterstation.json
