apiVersion: 1

datasources:
  - name: Wetter PostgreSQL
    uid: wetter-postgres
    type: postgres
    access: proxy
    isDefault: true
    url: wetter-postgres:5432
    user: weather
    database: weather

    jsonData:
      database: weather
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false

    secureJsonData:
      password: weather